name: canyoudumbass
version: 1.0-SNAPSHOT
author: Zen Wolf
main: me.zenisbestwolf.canyoudumbass.Main
description: fucking dumbass baby bitch cant even fucking mine stone wow need some congratulations stupid baby bitch
api-version: 1.15